### ISSUE TITLE
Testing: Invalid value handling

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/NumericDataTypes#16]
The [invalid-value-handling](https://github.com/omeka-s-modules/NumericDataTypes/tree/invalid-value-handling) branch should fix #15. If a persistent value is invalid, the data type will just render the raw value. On the edit page it should display an error above the form inputs, giving the user the chance to correct the value.

It's not the easiest thing to test since, ideally, invalid values should never be persisted, but you can test this by modifying the existing timestamp, interval, duration, and integer values directly in the database. Once they're in an invalid state, you should not see exceptions in the show or edit pages.

**Comment by zerocrates** [comment]
If you load the edit page with an invalid value present and save it, it gets deleted unless you've re-entered it.

I know _why_ it does that but it's unexpected.

**Comment by jimsafley** [comment]
A numeric value must be a valid format before it's hydrated, otherwise it's ignored. This behavior is the same as any other data type. The error message on the edit page gives the user a chance to correct the value.

**Comment by zerocrates** [comment]
On a more minor note, I'm not in love with the usage of inline styling for the errors... I believe this module already loads CSS so it should style things that way.

The disappearing thing isn't the most major thing in the world but I definitely found it surprising. (It happened when I'd already checked the behavior of an invalid date then went to add the other types.) In a big form it would be easy to miss your one chance to see that the value is invalid.

Since it shouldn't happen anyway it's not hugely important though, I guess. The only option I can think of to avoid the issue would be popping up a `confirm` or similar before form submit alerting the user (if there are error-marked fields that still don't have a value) that their data will be lost... but that may not be worth the effort in this case.

**Comment by jimsafley** [comment]
The most recent commits should fix the problems you mentioned.
